modLoader = "javafml"
loaderVersion = "[3,)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "merchantjs"
version = "1.0.1"
displayName = "MerchantJS"
authors = "Tower of Sighs"
description = "KubeJS addon that expands the trading system. Create fully customizable merchant trades anywhere, unlock trades selectively, and hook afterTrade/switchTrade events for both custom and vanilla merchants."

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.merchantjs]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.merchantjs]]
modId = "kubejs"
type = "required"
versionRange = "[26.1.2-8.0.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.merchantjs]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "merchantjs.mixins.json"
